Update PhysicsSamples to 0.51
Unity-Technologies/EntityComponentSystemSamples pull request #213
Opened 2022-06-29 13:52 UTC by josepmariapujol-unity

Update PhysicsSamples to DOTS - 0.51.
Using 2021.3.4f1LTS editor and URP 12.1.7.

2022-06-29 14:31 UTC, Drealmer requested changes

2022-06-29 14:32 UTC, Drealmer commented on PhysicsSamples/README.md
> +| Joints | <sub>Ragdoll.unity</sub> | Obligatory stack of ragdolls demo | Introductory  | ![Ragdoll](images/ragdolls.gif) |
(the ragdoll one)

2022-06-30 13:08 UTC, josepmariapujol-unity commented on PhysicsSamples/README.md
> +| Joints | <sub>Ragdoll.unity</sub> | Obligatory stack of ragdolls demo | Introductory  | ![Ragdoll](images/ragdolls.gif) |
Fixed

2022-06-30 13:20 UTC, Drealmer approved these changes
thanks for the update, lgtm

2022-07-01 14:03 UTC, merged